##  modules and Packages
## map(),filter(),lambda
## list and dictoinary comprehensions
## Numpy
## modules and package

In [1]:
import math

In [2]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of

## moduleName.funcName

In [3]:
math.sqrt(4)

2.0

In [4]:
math.pow(2,5)

32.0

In [5]:
math.radians(90)

1.5707963267948966

In [7]:
rad = math.radians(45)
rad

0.7853981633974483

In [8]:
math.cos(rad)

0.7071067811865476

In [12]:
1/(2 ** 0.5)

0.7071067811865475

In [9]:
math.ceil(8.9)

9

In [10]:
math.floor(8.9)

8

In [13]:
math.factorial(5)

120

## import moduleName as alaisName

In [14]:
import math as m

In [15]:
m.pow(5,2)

25.0

In [17]:
from math import sqrt

In [18]:
sqrt(4)

2.0

In [19]:
from math import sqrt,pow

In [20]:
pow(5,2)

25.0

In [21]:
from math import *

In [22]:
ceil(8.9)

9

In [24]:
import mymodule

In [25]:
mymodule.add(2,5)

7

In [26]:
mymodule.mul(2,5)

10

In [27]:
mymodule.pi

3.14

## Numpy

In [10]:
import numpy as np

In [11]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [12]:
n2 = np.array([1,2,3,4,5.0])
n2

array([1., 2., 3., 4., 5.])

In [13]:
type(n1)

numpy.ndarray

In [14]:
n1.dtype

dtype('int32')

In [15]:
n2.dtype

dtype('float64')

In [16]:
n1.ndim

1

In [37]:
d2 = np.array([[1,2],[3,4]])
d2

array([[1, 2],
       [3, 4]])

In [38]:
d2.ndim

2

In [17]:
n3 = np.arange(50)
n3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
n4 = np.arange(1,51,2)
n4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [21]:
n4.shape

(25,)

In [22]:
n4 = n4.reshape(5,5)

In [23]:
n4

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [25]:
n4[0]

array([1, 3, 5, 7, 9])

In [26]:
n4[0,2]

5

In [27]:
n4[:2,:2]

array([[ 1,  3],
       [11, 13]])

In [29]:
n = np.arange(1,51)
li = [i for i in range(1,51)]

print(n)
print(li)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [30]:
%timeit [i ** 2 for i in li]

20.9 µs ± 4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
%timeit n ** 2

623 ns ± 78.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Mathemathcal Operations

In [48]:
n1 = np.arange(1,11)
n2 = np.arange(1,11)

In [49]:
n1 + n2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
n1 * n2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
n1 == n2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [52]:
np.logical_and(n1,n2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [53]:
np.logical_not(n1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [54]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.logical_and(np.array([0,1,2]),np.array([2,3,4]))

array([False,  True,  True])

In [58]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
np.ones(10,dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [61]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
d = np.diag([1,2,3,4,5])
d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [67]:
d.diagonal()

array([1, 2, 3, 4, 5])

In [68]:
n4.diagonal()

array([ 1, 13, 25, 37, 49])

In [69]:
np.hstack((d,n4))

array([[ 1,  0,  0,  0,  0,  1,  3,  5,  7,  9],
       [ 0,  2,  0,  0,  0, 11, 13, 15, 17, 19],
       [ 0,  0,  3,  0,  0, 21, 23, 25, 27, 29],
       [ 0,  0,  0,  4,  0, 31, 33, 35, 37, 39],
       [ 0,  0,  0,  0,  5, 41, 43, 45, 47, 49]])

In [71]:
np.vstack((d,n4))

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  5],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [73]:
s1 = np.hstack((d,n4))
s1

array([[ 1,  0,  0,  0,  0,  1,  3,  5,  7,  9],
       [ 0,  2,  0,  0,  0, 11, 13, 15, 17, 19],
       [ 0,  0,  3,  0,  0, 21, 23, 25, 27, 29],
       [ 0,  0,  0,  4,  0, 31, 33, 35, 37, 39],
       [ 0,  0,  0,  0,  5, 41, 43, 45, 47, 49]])

In [78]:
s2 = np.vstack((d,n4))
s2

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  5],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [79]:
print(d)
print(n4)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [80]:
q1 = np.array([1,2,3,4])
q2 = np.array([4,3,2,1])

q1 * q2

array([4, 6, 6, 4])

In [83]:
s4 = np.dot(s1,s2)
s4

array([[ 726,  775,  825,  875,  925],
       [1775, 1929, 2075, 2225, 2375],
       [2825, 3075, 3334, 3575, 3825],
       [3875, 4225, 4575, 4941, 5275],
       [4925, 5375, 5825, 6275, 6750]])

In [77]:
print(s1)
print(s2)

[[ 1  0  0  0  0  1  3  5  7  9]
 [ 0  2  0  0  0 11 13 15 17 19]
 [ 0  0  3  0  0 21 23 25 27 29]
 [ 0  0  0  4  0 31 33 35 37 39]
 [ 0  0  0  0  5 41 43 45 47 49]]
[[ 1  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0  5]
 [ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [81]:
np.dot(s2,s1)

array([[   1,    0,    0,    0,    0,    1,    3,    5,    7,    9],
       [   0,    4,    0,    0,    0,   22,   26,   30,   34,   38],
       [   0,    0,    9,    0,    0,   63,   69,   75,   81,   87],
       [   0,    0,    0,   16,    0,  124,  132,  140,  148,  156],
       [   0,    0,    0,    0,   25,  205,  215,  225,  235,  245],
       [   1,    6,   15,   28,   45,  725,  775,  825,  875,  925],
       [  11,   26,   45,   68,   95, 1775, 1925, 2075, 2225, 2375],
       [  21,   46,   75,  108,  145, 2825, 3075, 3325, 3575, 3825],
       [  31,   66,  105,  148,  195, 3875, 4225, 4575, 4925, 5275],
       [  41,   86,  135,  188,  245, 4925, 5375, 5825, 6275, 6725]])

In [84]:
s4.max()

6750

In [85]:
s4.min()

726

In [87]:
s4.sum()

83180

In [88]:
s4.argmax()

24

In [89]:
s4

array([[ 726,  775,  825,  875,  925],
       [1775, 1929, 2075, 2225, 2375],
       [2825, 3075, 3334, 3575, 3825],
       [3875, 4225, 4575, 4941, 5275],
       [4925, 5375, 5825, 6275, 6750]])

In [90]:
s4.argmin()

0

In [91]:
s4.prod()

-1572060584

In [92]:
s4.cumsum()

array([  726,  1501,  2326,  3201,  4126,  5901,  7830,  9905, 12130,
       14505, 17330, 20405, 23739, 27314, 31139, 35014, 39239, 43814,
       48755, 54030, 58955, 64330, 70155, 76430, 83180], dtype=int32)

In [93]:
c = np.array([2 + 4j])
c.dtype

dtype('complex128')

In [95]:
c = np.array([2 + 4j,6,7,8,9])
c

array([2.+4.j, 6.+0.j, 7.+0.j, 8.+0.j, 9.+0.j])

In [96]:
d.repeat(2,axis = 0)

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 5]])

In [97]:
d.repeat(2,axis = 1)

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 5]])

In [99]:
np.equal(d,d)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [100]:
d.tolist()

[[1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]

In [101]:
j = np.random.rand(5,5)
j

array([[0.58649353, 0.08123604, 0.81054952, 0.75330525, 0.08218598],
       [0.76439052, 0.44066771, 0.04365601, 0.08980499, 0.96484947],
       [0.25113086, 0.04487454, 0.52960212, 0.98425643, 0.21762296],
       [0.67639296, 0.65403394, 0.13602455, 0.42467203, 0.87167483],
       [0.69967481, 0.62020615, 0.69454038, 0.58971772, 0.89305375]])

In [113]:
j.sort(axis = 0)
j

array([[0.04365601, 0.08218598, 0.25113086, 0.52960212, 0.81054952],
       [0.04487454, 0.08980499, 0.44066771, 0.67639296, 0.87167483],
       [0.08123604, 0.21762296, 0.58649353, 0.69967481, 0.89305375],
       [0.13602455, 0.42467203, 0.65403394, 0.75330525, 0.96484947],
       [0.58971772, 0.62020615, 0.69454038, 0.76439052, 0.98425643]])

In [112]:
j.sort(axis = 1)
j

array([[0.04365601, 0.08218598, 0.25113086, 0.52960212, 0.81054952],
       [0.04487454, 0.08980499, 0.44066771, 0.67639296, 0.87167483],
       [0.08123604, 0.21762296, 0.58649353, 0.69967481, 0.89305375],
       [0.13602455, 0.42467203, 0.65403394, 0.75330525, 0.96484947],
       [0.58971772, 0.62020615, 0.69454038, 0.76439052, 0.98425643]])

In [106]:
np.median(j)

0.5897177197794867

In [107]:
j.mean()

0.5161846817746671

In [108]:
np.random.randint(1,100)

93

In [109]:
np.random.randn(5,5)

array([[-1.62046391, -2.74513693,  0.90221901, -0.43082127,  0.30022903],
       [-1.24641581,  0.32105292, -0.56395403, -0.56211102,  0.48340449],
       [-1.45699694,  0.17506208,  1.69360234, -0.8631964 ,  0.09868347],
       [-1.65239533,  1.48681864,  0.14415   , -0.19648209,  1.08288448],
       [ 1.92337584,  1.69210999, -0.18077352, -1.0396009 ,  0.08057647]])